#!/bin/zsh
zmodload zsh/parameter
NPROCSMX=4
filename=$1
for cmd in ${(f)"$(<$filename)"}; do
    while ((  ${#jobstates} >= $NPROCSMX ))  { sleep 10; }  # limit the number of jobs
    echo "Running ${cmd}";
    (eval nice ${cmd}) &
done